[project]
name = "codes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.3",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "supabase>=2.11.0",
]
